# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS SES controller is a service controller for managing SES resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon SES
description: |-
  Manage Amazon Simple Email Service (SES) resources in AWS from within your Kubernetes cluster.


  **About Amazon SES**


  Amazon Simple Email Service (SES) is an email platform that provides an easy, cost-effective way for you to send and receive email using your own email addresses and domains.
  
  For example, you can send marketing emails such as special offers, transactional emails such as order confirmations, and other types of correspondence such as newsletters.
  When you use Amazon SES to receive mail, you can develop software solutions such as email autoresponders, email unsubscribe systems, and applications that generate customer
  support tickets from incoming emails.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: EmailTemplate
  spec: '{}'
maintainers:
- name: "ses maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon SES Developer Resources
  url: https://aws.amazon.com/ses/developer-resources/
